/**
 * ESLint — SP-122, the other half of the story `prettier.config.mjs` opens.
 *
 * Prettier and ESLint are not alternatives and neither one covers for the
 * other. Prettier decides where the line breaks; ESLint is the only thing here
 * that reads what the code does. Both run in CI, in that order.
 *
 * Flat config, because Next 16 removed `next lint` and eslint-config-next 16
 * ships flat arrays rather than an `extends` string. There is no .eslintrc.
 *
 * ORDER IS LOAD-BEARING. `prettier` must stay after the two Next configs: it is
 * nothing but ~360 rules switched off, and its whole job is to disable the
 * stylistic rules the earlier configs turn on so the two tools cannot disagree
 * about the same line. Move it up and Prettier and ESLint start fighting over
 * indentation, with CI failing whichever one ran second.
 *
 * ESLint does NOT read .gitignore the way Prettier does, so build output has to
 * be listed here by hand — anything ignored in .gitignore that contains JS
 * belongs in the ignores block below or it gets linted.
 */

import next from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier/flat';

export default [
    {
        ignores: [
            '.next/**',
            'out/**',
            'build/**',
            '.turbo/**',
            'coverage/**',
            'test-results/**',
            'playwright-report/**',
            'blob-report/**',
            'playwright/.cache/**',
            // Written by the Supabase CLI, not by anyone here.
            'supabase/.temp/**',
            // Generated by `next build` and regenerated whenever it is deleted.
            'next-env.d.ts',
        ],
    },

    ...next,
    ...nextTypescript,

    prettier,

    {
        name: 'skillpath/config-files',
        files: ['*.config.mjs', '*.config.ts'],
        rules: {
            // `export default { … }` is the only shape a config file may take;
            // the rule is asking for a named variable that nothing would read.
            'import/no-anonymous-default-export': 'off',
        },
    },

    {
        name: 'skillpath/project',
        rules: {
            /*
             * `any` is banned by ARCHITECTURE.md §8. Until this line the ban
             * was a convention that nothing enforced, which is the kind of
             * rule that holds right up until the afternoon someone is in a
             * hurry.
             *
             * `error` and not `warn` because it costs nothing to hold the line
             * here: there is not one `any` in the 269 files this config lints,
             * so the rule starts green and every future hit is new code. The
             * escape hatch is `unknown` plus a narrowing check, and where that
             * genuinely will not do, an `eslint-disable-next-line` with a
             * comment saying why — same bar as the two suppressions already in
             * the tree (app/error.tsx, components/ui/avatar.tsx).
             */
            '@typescript-eslint/no-explicit-any': 'error',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'all' },
            ],
            /*
             * Downgraded to a warning rather than switched off, and this is a
             * deliberate compromise with an expiry date on it.
             *
             * The rule is new in eslint-plugin-react-hooks 7 and it is right in
             * general: setState in an effect body causes a second render pass.
             * Every one of the seven current hits is a pattern that was chosen
             * on purpose, though, and they are two different patterns:
             *
             *   theme-toggle, user-nav, mobile-nav — the mounted guard. The
             *     server cannot know the browser's theme, so the first paint
             *     renders a neutral value and the effect swaps in the real one.
             *     Rendering the true value on the server is a hydration
             *     mismatch, which is a worse bug than an extra render.
             *
             *   name-form, profile-header, question-form, interests-section —
             *     closing an inline editor once useActionState reports success.
             *     This one is genuinely worth revisiting; the action's own
             *     result is available at render time.
             *
             * `error` would mean rewriting seven working components inside the
             * change that introduces the linter, which is how a first ESLint
             * pass gets reverted. `off` would mean never seeing the rule fire
             * on code written next week. Warn keeps it visible and keeps CI
             * honest about what is actually broken versus what is merely known.
             */
            'react-hooks/set-state-in-effect': 'warn',
        },
    },
];
