-- skill_categories.category_id: GENERATED ALWAYS -> GENERATED BY DEFAULT.
--
-- ---------------------------------------------------------------------------
-- CE S-A STRICAT.
-- ---------------------------------------------------------------------------
--
--   npm run seed:e2e
--   Creating category "General Knowledge" failed:
--     cannot insert a non-DEFAULT value into column "category_id"
--
-- `GENERAL_KNOWLEDGE_CATEGORY_ID` este 0 (lib/domain/constants.ts). Zero nu e o
-- valoare pe care secvența o poate produce vreodată — identity începe de la 1 —
-- deci rândul-sentinelă TREBUIE inserat cu id explicit. Iar `generated always`
-- refuză exact asta.
--
-- ---------------------------------------------------------------------------
-- DE CE NU SE REZOLVĂ ÎN SEED.
-- ---------------------------------------------------------------------------
--
-- În SQL brut soluția e `OVERRIDING SYSTEM VALUE`, și de aceea supabase/seed.sql
-- funcționează. `scripts/seed.mjs` merge însă prin PostgREST, care nu poate
-- emite clauza aceea: nu există nicio formă de `.insert()` care s-o adauge. Deci
-- ori se schimbă coloana, ori seed-ul JS nu poate scrie niciodată sentinela.
--
-- `by default` păstrează generarea automată pentru toate celelalte inserturi —
-- nimeni nu trimite `category_id`, în afară de seed — și o permite pe cea
-- explicită când e trimisă. Nu slăbește nimic: coloana rămâne identity, cheie
-- primară, iar unicitatea e tot a secvenței.
--
-- Doar skill_categories. `questions.question_id` rămâne `generated always`:
-- singurul lucru care îi forțează id-urile e supabase/seed.sql, care e SQL brut
-- și are deja `OVERRIDING SYSTEM VALUE`.

alter table public.skill_categories
    alter column category_id set generated by default;

-- Secvența nu știe despre rândurile inserate explicit, deci după ce seed-ul
-- scrie categoria 0 următorul insert automat ar putea încerca 1 și să se
-- lovească de o categorie deja existentă cu acel id. Repornirea de deasupra
-- celui mai mare id folosit ține cele două lumi separate.
select setval(
    pg_get_serial_sequence('public.skill_categories', 'category_id'),
    greatest(coalesce((select max(category_id) from public.skill_categories), 0), 1)
);
